//importing necessary libraries
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

//AdminLogin.java inherits the class from the JFrame STL class in order to make it a JFrame Form to create UI
public class AdminLogin extends javax.swing.JFrame {

    //public constructor of the AdminLogin CLass
    public AdminLogin() {
        initComponents();
    }

    /**NETBEANS GENERATED CODE FROM THE FRONT END DESIGN CONSOLE
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTitle = new javax.swing.JLabel();
        adminUserInput = new javax.swing.JTextField();
        passwordTitle = new javax.swing.JLabel();
        adminPasswordInput = new javax.swing.JPasswordField();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        adminLoginButton = new javax.swing.JButton();
        returnToIndexButton = new javax.swing.JButton();
        adLoginBackground = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameTitle.setText("Username");
        getContentPane().add(usernameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, -1, -1));

        adminUserInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(adminUserInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, 300, -1));

        passwordTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordTitle.setText("Password");
        getContentPane().add(passwordTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 660, -1, -1));

        adminPasswordInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(adminPasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 690, 300, -1));

        showPasswordCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showPasswordCheckBox.setText("Show Password");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(showPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 730, 127, -1));

        adminLoginButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adminLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginsmall.png"))); // NOI18N
        adminLoginButton.setText("Log in");
        adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(adminLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 770, -1, -1));

        returnToIndexButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        returnToIndexButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/returnsmall.png"))); // NOI18N
        returnToIndexButton.setText("Back");
        returnToIndexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToIndexButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnToIndexButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 770, -1, -1));
        getContentPane().add(adLoginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundIndex.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //RETURN BUTTON EVENT
    private void returnToIndexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToIndexButtonActionPerformed
        //if the user clicks on the return button, they will return to the main landing page (index.java)
        setVisible(false);
        new Index().setVisible(true);
    }//GEN-LAST:event_returnToIndexButtonActionPerformed

    //ADMIN LOGIN BUTTON ACTION SET UP
    private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginButtonActionPerformed
        //will check if the admin login credentials match in order to be able to login
        //creating an admin account with the username 'mariaclarin' with the password 'admin123'
        if(adminUserInput.getText().equals("mariaclarin")&& adminPasswordInput.getText().equals("admin123")){
            
            //if the credentials match, the user will be able to access the admin homepage. 
            //it means that the login is successful
            setVisible(false);
            new AdminHomePage().setVisible(true);
        }
        
        //If the credentials doesnt match, a popup message will appear stating incorrect username or password.
        else
        {
            ImageIcon icon=new ImageIcon("passWrong.PNG");
            JOptionPane.showMessageDialog(null,"<html>Incorrect Username <br> or Password</b></html>", "Show", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_adminLoginButtonActionPerformed

    //SHOW PASSWORD CHECKBOX ACTION SET UP
    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        // if the show password checkbox is selected, it will show the password chars
        if(showPasswordCheckBox.isSelected()){
            adminPasswordInput.setEchoChar((char)0);
        }
        
        //if it is not selected, it will show the individual chars as * 
        else
        {
            adminPasswordInput.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed
    
    //RUN COMMAND GENERATED BY NETBEANS
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }
    
    //JFrame Variables generated with the front end design console from Netbeans
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adLoginBackground;
    private javax.swing.JButton adminLoginButton;
    private javax.swing.JPasswordField adminPasswordInput;
    private javax.swing.JTextField adminUserInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel passwordTitle;
    private javax.swing.JButton returnToIndexButton;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JLabel usernameTitle;
    // End of variables declaration//GEN-END:variables
}
