//importing necessary libraries
import java.sql.*;
import SQLManage.Connector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

//AdminDeleteQuestion.java inherits the class from the JFrame STL in order to make a JFrame Form to create UI
public class AdminDeleteQuestion extends javax.swing.JFrame {
    
    //public constructor for the AdminDeleteQuestion Class
    public AdminDeleteQuestion() {
        initComponents();
    }

    
    /**NETBEANS GENERATED CODE FROM THE FRONT END DESIGN CONSOLE
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteTitle = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        questionIDTitle = new javax.swing.JLabel();
        questionTitle = new javax.swing.JLabel();
        option1Title = new javax.swing.JLabel();
        option2Title = new javax.swing.JLabel();
        option3Title = new javax.swing.JLabel();
        option4Title = new javax.swing.JLabel();
        answerTitle = new javax.swing.JLabel();
        questionIDInputField = new javax.swing.JTextField();
        questionInputField = new javax.swing.JTextField();
        opt1InputField = new javax.swing.JTextField();
        opt2InputField = new javax.swing.JTextField();
        opt3InputField = new javax.swing.JTextField();
        opt4InputField = new javax.swing.JTextField();
        answerInputField = new javax.swing.JTextField();
        deleteAllButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        deleteTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletemenuicon.png"))); // NOI18N
        deleteTitle.setText("Delete Question");
        getContentPane().add(deleteTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1920, 10));

        questionIDTitle.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        questionIDTitle.setText("Question ID :");
        getContentPane().add(questionIDTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 250, -1, -1));

        questionTitle.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        questionTitle.setText("Question :");
        getContentPane().add(questionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 290, -1, -1));

        option1Title.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        option1Title.setText("Option 1 :");
        getContentPane().add(option1Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 333, -1, -1));

        option2Title.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        option2Title.setText("Option 2 :");
        getContentPane().add(option2Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 376, -1, -1));

        option3Title.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        option3Title.setText("Option 3 :");
        getContentPane().add(option3Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 419, -1, -1));

        option4Title.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        option4Title.setText("Option 4 :");
        getContentPane().add(option4Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 462, -1, -1));

        answerTitle.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        answerTitle.setText("Answer :");
        getContentPane().add(answerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 505, -1, -1));

        questionIDInputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(questionIDInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 180, -1));

        questionInputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(questionInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 289, 1520, -1));

        opt1InputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(opt1InputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 332, 1520, -1));

        opt2InputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(opt2InputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 375, 1520, -1));

        opt3InputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(opt3InputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 418, 1520, -1));

        opt4InputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(opt4InputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 461, 1520, -1));

        answerInputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(answerInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 504, 1520, -1));

        deleteAllButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletemenuicon.png"))); // NOI18N
        deleteAllButton.setText("Delete All Questions");
        deleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteAllButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 550, -1, -1));

        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletemenuicon.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, -1, -1));

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, -1, -1));

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchsmall.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addQuestionBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //EXIT BUTTON EVENT
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // when the user clicks on the exit button, they will return to the AdminHomePage while the 
        // AdminDeleteQuestions page will disappear.
        AdminHomePage.open=0;
        setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    
    
    
    //DELETE BUTTON EVENT
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // creating the variable 'id' to store the user inputs from the questionIDInputField
        String id = questionIDInputField.getText();
        
        //The try block commands will establish a connection between this file and the mysql database made for Quizzen
        try
        {
            Connection con= Connector.getCon();
            PreparedStatement ps = con.prepareStatement("delete from question where id=?"); //declaring the query into the mysql database
            
            //inserting the data stored in the previously declared variables into the corresponding collumns of data in a row
            ps.setString(1, id);
            ps.executeUpdate(); //executing the update in the mysql database
            
            //Once the deletion is complete, a new JFrame popup will appear with the successful message.
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Successfully Deleted");
            
            //Once the user exits the Jframe popup, the AdminDeleteQuestion Page will refresh.
            setVisible(false);
            new AdminDeleteQuestion().setVisible(true);
        }
        
        //a catch block to go alongside the try block if the try block fails which catches an exception if an error occurs
        catch(Exception e)
        {
            //displays a JFrame that is basically nothing, if the catch block is activated, I take it as an indication that there is an error
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    //CLEAR BUTTON EVENT
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        //when the user presses the clear button, they will clear every single input field available on the screen
        //this will not make changes to the mysql database
        questionIDInputField.setText("");
        questionInputField.setText("");
        opt1InputField.setText("");
        opt2InputField.setText("");
        opt3InputField.setText("");
        opt4InputField.setText("");
        answerInputField.setText("");
        questionIDInputField.setEditable(true);
    }//GEN-LAST:event_clearButtonActionPerformed

    //SEARCH BUTTON EVENT
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // a string variable to store the user input in the questionIDInputField
        String id = questionIDInputField.getText();
        
        //the try block commands will establish a connection between this file and the mysql database made for Quizzen
        try
        {
            Connection con = Connector.getCon();
            Statement st= con.createStatement(); //creating a statement to declare into query
            
            //executing the query command. Selecting the entire row where the questionID matches the data in the collumn id
            ResultSet rs = st.executeQuery("select *from question where id='"+id+"'"); 
            
            //if the mysql database comes up with a result
            if(rs.next()){
                //this if statement will set the text in the input fields according to the data fetched in the mysql database.
                questionInputField.setText(rs.getString(2));
                opt1InputField.setText(rs.getString(3));
                opt2InputField.setText(rs.getString(4));
                opt3InputField.setText(rs.getString(5));
                opt4InputField.setText(rs.getString(6));
                answerInputField.setText(rs.getString(7));
                questionIDInputField.setEditable(false);
            }
            else
            {
                //if the mysql database comes up with no result, a popup message will appear to state that the questionID is invalid
                JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf, "Question ID not found.");
            }
        }
        
        //a catch block to go alongside the try block if the try block fails which catches an exception if an error occurs.
        //displays a JFrame that is basically nothing. If the catch block is activated, i take it as an indication that there is an error.
        catch(Exception e)
        {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    //DELETE BUTTON EVENT
    private void deleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllButtonActionPerformed
        // if the user clicks on the delete button, a JFrame confirm dialog will appear to ask for user confirmation.
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int userConfirmation=JOptionPane.showConfirmDialog(jf, "Are you sure you want to delete ALL QUESTIONS?", "Select", JOptionPane.YES_NO_OPTION);
        
        //if the user clicks the button Yes (the syntax ==0)
        if(userConfirmation==0)
        {
            //This try block will run to establish a connection between this file and the mysql database made for Quizzen
            try
            {
                Connection con= Connector.getCon();
                PreparedStatement ps = con.prepareStatement("delete from question"); //declaring the query into the mysql database to delete all rows from the table 'question'
                
                //executing the update in the mysql database
                ps.executeUpdate();
                
                //A new JFrame message dialog will appear and show the success message.
                JFrame jf1 = new JFrame();
                jf1.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf1, "Successfully Deleted");
                
                //once the user exits the JFrame popup, the AdminDeleteQuestion page will refresh
                setVisible(false);
                new AdminDeleteQuestion().setVisible(true);
            }
            
            //a catch block to go alongside the try block if the try block fails which catches an exception if an error occurs.
            catch(Exception e)
            {
                //displays a JFrame that is basically nothing. If the catch block is activated, I take it as an indication that there is an error.
                JFrame jf2 = new JFrame();
                jf2.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf2, e);
            } 
        } 
    }//GEN-LAST:event_deleteAllButtonActionPerformed

    //RUN COMMAND GENERATED BY NETBEANS
    public static void main(String args[]) {
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDeleteQuestion().setVisible(true);
            }
        });
    }
    
    //JFrame Variables generated with the front end design console from Netbeans.
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerInputField;
    private javax.swing.JLabel answerTitle;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel deleteTitle;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField opt1InputField;
    private javax.swing.JTextField opt2InputField;
    private javax.swing.JTextField opt3InputField;
    private javax.swing.JTextField opt4InputField;
    private javax.swing.JLabel option1Title;
    private javax.swing.JLabel option2Title;
    private javax.swing.JLabel option3Title;
    private javax.swing.JLabel option4Title;
    private javax.swing.JTextField questionIDInputField;
    private javax.swing.JLabel questionIDTitle;
    private javax.swing.JTextField questionInputField;
    private javax.swing.JLabel questionTitle;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
