//importing necessary libraries
import java.sql.*;
import SQLManage.Connector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

//AdminUpdateQuestion.java inherits the class from the JFrame STL in order to make it a JFrame form to create UI
public class AdminUpdateQuestion extends javax.swing.JFrame {
    
    //public constructor for the AdminUpdateQuestion Class
    public AdminUpdateQuestion() {
        initComponents();
    }

    /**NETBEANS GENERATED CODE FROM THE FRONT END DESIGN CONSOLE
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateTitle = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        questionIDTitle = new javax.swing.JLabel();
        questionTitle = new javax.swing.JLabel();
        option1Title = new javax.swing.JLabel();
        option2Title = new javax.swing.JLabel();
        option3Title = new javax.swing.JLabel();
        option4Title = new javax.swing.JLabel();
        answerTitle = new javax.swing.JLabel();
        questionIDInputField = new javax.swing.JTextField();
        questionInputField = new javax.swing.JTextField();
        opt1InputField = new javax.swing.JTextField();
        opt2InputField = new javax.swing.JTextField();
        opt3InputField = new javax.swing.JTextField();
        opt4InputField = new javax.swing.JTextField();
        answerInputField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        updateTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updatemenuicon.png"))); // NOI18N
        updateTitle.setText("Update Question");
        getContentPane().add(updateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1920, 10));

        questionIDTitle.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        questionIDTitle.setText("Question ID :");
        getContentPane().add(questionIDTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 250, -1, -1));

        questionTitle.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        questionTitle.setText("Question :");
        getContentPane().add(questionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 290, -1, -1));

        option1Title.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        option1Title.setText("Option 1 :");
        getContentPane().add(option1Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 333, -1, -1));

        option2Title.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        option2Title.setText("Option 2 :");
        getContentPane().add(option2Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 376, -1, -1));

        option3Title.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        option3Title.setText("Option 3 :");
        getContentPane().add(option3Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 419, -1, -1));

        option4Title.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        option4Title.setText("Option 4 :");
        getContentPane().add(option4Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 462, -1, -1));

        answerTitle.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        answerTitle.setText("Answer :");
        getContentPane().add(answerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 505, -1, -1));

        questionIDInputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(questionIDInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 180, -1));

        questionInputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(questionInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 289, 1520, -1));

        opt1InputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(opt1InputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 332, 1520, -1));

        opt2InputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(opt2InputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 375, 1520, -1));

        opt3InputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(opt3InputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 418, 1520, -1));

        opt4InputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(opt4InputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 461, 1520, -1));

        answerInputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(answerInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 504, 1520, -1));

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updatemenuicon.png"))); // NOI18N
        saveButton.setText("Save Updates");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, -1, -1));

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, -1));

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchsmall.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addQuestionBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //SAVE BUTTON EVENT
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // variables to store user input from the input field
        String id = questionIDInputField.getText();
        String name = questionInputField.getText();
        String opt1 = opt1InputField.getText();
        String opt2 = opt2InputField.getText();
        String opt3 = opt3InputField.getText();
        String opt4 = opt4InputField.getText();
        String answer = answerInputField.getText();
        
        //the try command will establish a connection between this file and the mysql database for quizzen
        try
        {
            Connection con= Connector.getCon();
            
            //declaring the query into the mysql database to update the question table according to the corresponding data in the row where the id matches the user input
            PreparedStatement ps = con.prepareStatement("update question set name=?, opt1=?, opt2=?, opt3=?, opt4=?, answer=?, id=? where id="+id+"");
            ps.setString(1, name);
            ps.setString(2, opt1);
            ps.setString(3, opt2);
            ps.setString(4, opt3);
            ps.setString(5, opt4);
            ps.setString(6, answer);
            ps.setString(7, id);
            
            //executing the update. After the update, a pop up message will appear
            ps.executeUpdate();
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Successfully Updated");
            
            //once the user exits the popup message, the AdminUpdateQuestion page will refresh
            setVisible(false);
            new AdminUpdateQuestion().setVisible(true);
        }
        
        //a catch block to go alongside the try block if the try block fails which catches an exception if an error orccurs
        catch(Exception e)
        {
            //displays a JFrame that is basically nothing. If the catch block is activated, I take it as an indication that there is an error
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }//GEN-LAST:event_saveButtonActionPerformed
  
    //CLEAR BUTTON EVENT
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // if the user clicks on the clear button, the program will clear every input field available on the page.
        questionIDInputField.setText("");
        questionInputField.setText("");
        opt1InputField.setText("");
        opt2InputField.setText("");
        opt3InputField.setText("");
        opt4InputField.setText("");
        answerInputField.setText("");
        questionIDInputField.setEditable(true);
    }//GEN-LAST:event_clearButtonActionPerformed
  
    //EXIT BUTTON EVENT
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // if the user clicks on the exit button, they will return to the AdminHomePage
        AdminHomePage.open=0;
        setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    //SEARCH BUTTON EVENT
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        //a variable to store the user input from the questionIDInputField
        String id = questionIDInputField.getText();
        
        //the try block commands will establish a connection between this file and the mysql database made for Quizzen
        try
        {
            Connection con = Connector.getCon();
            
            //creating a statement to declare as a query for the mysql database
            Statement st= con.createStatement();
            
            //executing the query to select the data from the row in the question table where the id matches the user input
            ResultSet rs = st.executeQuery("select *from question where id='"+id+"'");
            
            //if the mysql database comes up with a result
            if(rs.next()){
                //the input fields will display the fetched data from the database
                questionInputField.setText(rs.getString(2));
                opt1InputField.setText(rs.getString(3));
                opt2InputField.setText(rs.getString(4));
                opt3InputField.setText(rs.getString(5));
                opt4InputField.setText(rs.getString(6));
                answerInputField.setText(rs.getString(7));
                questionIDInputField.setEditable(false);
            }
            
            //if the mysql database does not come up with a result
            else
            {
                //a JFrame popup stating the ID doesnt exist will appear
                JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf, "Question ID not found.");
            }
        }
        
        //a catch block to go alongside the try block
        catch(Exception e)
        {
            //displays a JFrame that is basically nothing. If the catch block is activated, I take it as an indication that there is an error
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    //RUN COMMAND GENERATED BY NETBEANS
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUpdateQuestion().setVisible(true);
            }
        });
    }

    //JFrame Variables generated with the front end design console from Netbeans
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerInputField;
    private javax.swing.JLabel answerTitle;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField opt1InputField;
    private javax.swing.JTextField opt2InputField;
    private javax.swing.JTextField opt3InputField;
    private javax.swing.JTextField opt4InputField;
    private javax.swing.JLabel option1Title;
    private javax.swing.JLabel option2Title;
    private javax.swing.JLabel option3Title;
    private javax.swing.JLabel option4Title;
    private javax.swing.JTextField questionIDInputField;
    private javax.swing.JLabel questionIDTitle;
    private javax.swing.JTextField questionInputField;
    private javax.swing.JLabel questionTitle;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel updateTitle;
    // End of variables declaration//GEN-END:variables
}
