//importing necessary libraries
import java.sql.*;
import SQLManage.Connector;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.JFrame;

//AdminViewStudentResult.java inherits the class from the JFrame STL in order to make it a JFrame Form to create UI
public class AdminViewStudentResult extends javax.swing.JFrame {

    //public constructor of the AdminViewStudentResult class
    public AdminViewStudentResult() {
        initComponents();
        
        //the try block commands will establish a connection between this file and the mysql database made for Quizzen
        try
        {
            Connection con = Connector.getCon();
            Statement st = con.createStatement(); //create statement to execute to query
            
            //executing a query to select all the rows in the student table and displaying them into the studentTable
            ResultSet rs = st.executeQuery("select *from student");
            studentTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        //a catch block to go alongside the try block if the try block fails which catches an exception if an error occors
        catch(Exception e){
            //a message dialog that contains nothing, only for error handling purposes
            JOptionPane.showMessageDialog(null, e);
        }
    }
    

    /**NETBEANS GENERATED CODE FROM THE FRONT END DESIGN CONSOLE
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewStudentResultTitle = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        filterTitle = new javax.swing.JLabel();
        filterInputField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewStudentResultTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        viewStudentResultTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studentresults.png"))); // NOI18N
        viewStudentResultTitle.setText("View Student Results");
        getContentPane().add(viewStudentResultTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1760, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1920, 10));

        filterTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        filterTitle.setText("Filter Students By Marks :");
        getContentPane().add(filterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        filterInputField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        filterInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterInputFieldKeyReleased(evt);
            }
        });
        getContentPane().add(filterInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 221, 160, 40));

        studentTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        )
    );
    studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            studentTableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(studentTable);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 1742, 410));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addQuestionBackground.png"))); // NOI18N
    jLabel1.setText("jLabel1");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //EXIT BUTTON EVENT
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // if the user clicks the exit button, they will return to the AdminHomePage page
        AdminHomePage.open=0;
        setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    //FILTER INPUT FIELD EVENT
    private void filterInputFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterInputFieldKeyReleased
        //if the filterInputField is empty, the score variable will be set as 0
        int score;
        if(filterInputField.getText().equals("")){
            score=0;
        }
        
        //if the filterInputField is not empty, the score variable will take value of the input and change it into int
        else
            score=Integer.parseInt(filterInputField.getText());
        
        //the try block commands will establish a connection between this file and the mysql database made for Quizzen
        try
        {
            Connection con = Connector.getCon();
            Statement st = con.createStatement(); //a create statement to declare to the query of the mysql database
            
            //executing the query to select all data in the row where the score variable is >= the data in the Marks Collumn in the student table
            //then displaying it in the studentTable
            ResultSet rs = st.executeQuery("select *from student where Marks >="+score+"");
            studentTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        //a catch block to go alongside the try block to catch exception errors
        //will display a new JFrame popup message to indicate an error in the try block.
        catch(Exception e){
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }//GEN-LAST:event_filterInputFieldKeyReleased

    //STUDENT TABLE EDITABLE SETUP
    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        // if the user tries to edit the table in this form, a pop up message dialog will appear
        //stating that they can not do so.
        boolean edits = studentTable.isEditing();
        if(edits==false){
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "You can not edit this table in this form.");
        }
    }//GEN-LAST:event_studentTableMouseClicked

    //RUN COMMAND GENERATED BY NETBEANS
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewStudentResult().setVisible(true);
            }
        });
    }
    
    
    //JFrame variables generated with the front end design console from Netbeans
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField filterInputField;
    private javax.swing.JLabel filterTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable studentTable;
    private javax.swing.JLabel viewStudentResultTitle;
    // End of variables declaration//GEN-END:variables
}
