//importing necessary libraries
import java.text.SimpleDateFormat;
import java.sql.*;
import java.util.Date;
import SQLManage.Connector;
import javax.swing.JOptionPane;
        
//StudentLogin.java inherits the class from the JFrame STL in order to create the UI
public class StudentLogin extends javax.swing.JFrame {

    //public constructor for StudentLogin class
    public StudentLogin() {
        initComponents();
        
        //setting the text area to not be editable
        quizzenTextArea.setEditable(false);
        
        //creating a automated date generator and displaying it in a Jframe label
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        dateLabel.setText(dFormat.format(date));

    }

    /**NETBEANS GENERATED CODE FROM THE FRONT END DESIGN CONSOLE
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studDataFormTitle = new javax.swing.JLabel();
        dateTitle = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        nameTitle = new javax.swing.JLabel();
        classTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        genderTitle = new javax.swing.JLabel();
        studentIDNoTitle = new javax.swing.JLabel();
        contactNoTitle = new javax.swing.JLabel();
        emailTitle = new javax.swing.JLabel();
        addressTitle = new javax.swing.JLabel();
        nameInputField = new javax.swing.JTextField();
        classInputField = new javax.swing.JTextField();
        studentIDNoInputField = new javax.swing.JTextField();
        contactNoInputField = new javax.swing.JTextField();
        emailInputField = new javax.swing.JTextField();
        addressInputField = new javax.swing.JTextField();
        genderInput = new javax.swing.JComboBox<>();
        saveNextButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        quizzenTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studDataFormTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        studDataFormTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.png"))); // NOI18N
        studDataFormTitle.setText("Student Data Form");
        getContentPane().add(studDataFormTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        dateTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        dateTitle.setText("Date :");
        getContentPane().add(dateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, -1, -1));

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        dateLabel.setText("jLabel1");
        getContentPane().add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, -1, -1));

        returnButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 40, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1920, 10));

        nameTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        nameTitle.setText("Name ");
        getContentPane().add(nameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        classTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        classTitle.setText("Class");
        getContentPane().add(classTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 297, -1, -1));

        genderTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        genderTitle.setText("Gender ");
        getContentPane().add(genderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        studentIDNoTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        studentIDNoTitle.setText("Student ID No.");
        getContentPane().add(studentIDNoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        contactNoTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        contactNoTitle.setText("Contact No.");
        getContentPane().add(contactNoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        emailTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        emailTitle.setText("Email");
        getContentPane().add(emailTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        addressTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        addressTitle.setText("Address");
        getContentPane().add(addressTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        nameInputField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(nameInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 608, -1));

        classInputField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(classInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 608, -1));

        studentIDNoInputField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(studentIDNoInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 606, -1));

        contactNoInputField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(contactNoInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 606, -1));

        emailInputField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(emailInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 606, -1));

        addressInputField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(addressInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 606, -1));

        genderInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genderInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(genderInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 315, -1));

        saveNextButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        saveNextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveNextButton.setText("Save and Proceed");
        saveNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveNextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, -1, -1));

        quizzenTextArea.setColumns(20);
        quizzenTextArea.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        quizzenTextArea.setRows(5);
        quizzenTextArea.setText("Quizzen will be managing student and teacher activities related \nto class quiz activities.\nHave some fun in today's quiz and we wish you the best of luck.\nRemember that honesty is the best policy.\n\n\"The purpose of the quiz is not to shame or embarass anyone, \nbut to make sure everyone is on the same page.\"\n\t\t\t- Mark Goulston\n\n");
        jScrollPane1.setViewportView(quizzenTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 240, 680, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addQuestionBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //RETURN BUTTON EVENT
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // if the user clicks on the return button, they will return to the Index page (the initial starting page)
        setVisible(false);
        new Index().setVisible(true);
    }//GEN-LAST:event_returnButtonActionPerformed

    //SAVE NEXT BUTTON EVENT
    private void saveNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNextButtonActionPerformed
        // variables to store user inputs from the input fields
        String name = nameInputField.getText();
        String classInput = classInputField.getText();
        String gender = (String)genderInput.getSelectedItem();
        String studentID = studentIDNoInputField.getText();
        String contactNo = contactNoInputField.getText();
        String email = emailInputField.getText();
        String address = addressInputField.getText();
        String marks = "0"; 
        
        //the try block commands will establish a connection between this file and the mysql database made for quizzen
        try 
        {
            Connection con = Connector.getCon();
            
            // a prepared statement with the query to insert the values of the user input into the corresponding collumns in the student table
            PreparedStatement ps = con.prepareStatement("insert into student values(?,?,?,?,?,?,?,?)");
            ps.setString(1, name);
            ps.setString(2, classInput);
            ps.setString(3, gender);
            ps.setString(4, studentID);
            ps.setString(5, contactNo);
            ps.setString(6, email);
            ps.setString(7, address);
            ps.setString(8, marks);
            
            //executing the update and starting the StudentInstructions.java file while passing the studentID variable value as the parameter
            ps.executeUpdate();
            setVisible(false);
            new StudentInstructions(studentID).setVisible(true);
        }
        
        //a catch block to go alongside the try block to indicate any errors that might occur from the try block commands
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }    
    }//GEN-LAST:event_saveNextButtonActionPerformed

    //RUN COMMAND GENERATED BY NETBEANS
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogin().setVisible(true);
            }
        });
    }

    //JFrame variables generated by the front end design console in Netbeans
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressInputField;
    private javax.swing.JLabel addressTitle;
    private javax.swing.JTextField classInputField;
    private javax.swing.JLabel classTitle;
    private javax.swing.JTextField contactNoInputField;
    private javax.swing.JLabel contactNoTitle;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateTitle;
    private javax.swing.JTextField emailInputField;
    private javax.swing.JLabel emailTitle;
    private javax.swing.JComboBox<String> genderInput;
    private javax.swing.JLabel genderTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameInputField;
    private javax.swing.JLabel nameTitle;
    private javax.swing.JTextArea quizzenTextArea;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton saveNextButton;
    private javax.swing.JLabel studDataFormTitle;
    private javax.swing.JTextField studentIDNoInputField;
    private javax.swing.JLabel studentIDNoTitle;
    // End of variables declaration//GEN-END:variables
}
