//StudentInstructions.java inherits the class from the JFrame STL in order to create a UI
public class StudentInstructions extends javax.swing.JFrame {
    
    //a public attribute/variable to store the student ID
    public String studentID;

    //public default constructor for StudentsInstructions class
    public StudentInstructions() {
        initComponents();
    }
    
    //overloading the constructor for StudentsInstructions class by adding a parameter that is studentIDNo1
    public StudentInstructions(String studentIDNo1) {
        initComponents();
        //this constructor is mainly to pass the value of the student ID from the StudentLogin page to the next page (StudentQuiz.java)
        instructionText.setEditable(false);
        studentID = studentIDNo1;
    }
    
    
    /**NETBEANS GENERATED CODE FROM THE FRONT END DESIGN CONSOLE 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionsTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructionText = new javax.swing.JTextArea();
        startQuizButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionsTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        instructionsTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.png"))); // NOI18N
        instructionsTitle.setText("Instructions");
        getContentPane().add(instructionsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1920, 10));

        instructionText.setColumns(20);
        instructionText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        instructionText.setRows(5);
        instructionText.setText("During the course of the quiz;\n\n1. The student may or may not use his or her textbook, course notes, receive help from another student, or use outside source based on the teacher's \nregulation and requirements.\n\n2. Students may or may not use tools such as calculators, the Internet, or any other external tools to aid in the exam according to the teacher's regulation\nand requirements.\n\n3. Students must complete the quiz within the time frame allotted for the exam.\n\n4. Students must not stop the session and then attempt to return to it. Once a session is stopped, the student are not allowed to retake the quiz again. Unless\nallowed by the teacher.\n\nWe wish you the best of luck !");
        jScrollPane1.setViewportView(instructionText);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 1730, 460));

        startQuizButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startQuizButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        startQuizButton.setText("Start Quiz");
        startQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startQuizButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startQuizButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 690, -1, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addQuestionBackground.png"))); // NOI18N
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    //START QUIZ BUTTON EVENT
    private void startQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startQuizButtonActionPerformed
        // a button that runs the StudentQuiz.java file and exits the StudentInstructions.java file
        setVisible(false);
        new StudentQuiz(studentID).setVisible(true);
    }//GEN-LAST:event_startQuizButtonActionPerformed

    //RUN COMMAND GENERATED BY NETBEANS
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInstructions().setVisible(true);
            }
        });
    }

    //JFrame variables generated with the front end design console from netbeans
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JTextArea instructionText;
    private javax.swing.JLabel instructionsTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton startQuizButton;
    // End of variables declaration//GEN-END:variables
}
